### ISSUE TITLE
Dependency versions locked too tightly

### ISSUE THREAD

**Issue by andrewaylett** [nlopes/libhoney-rust#30]
Per https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries I see you've not got a Cargo.lock, but we're using the `=` requirements specifier for all our dependencies, which can still cause problems.

My specific issue is that the new 2.0.0 release of actix-web depends on a strictly later version of serde, meaning that my project can't now contain both the new release of actix-web and libhoney-rust.

Can we relax the dependencies to caret dependencies, and trust semver to do the right thing unless proven otherwise?

**Comment by nlopes** [comment]
Sorry @andrewaylett. Have been away and for some reason this didn't pop-up in my email. I'm ok with relaxing at least for now..
